### ISSUE TITLE
连接服务器时弹出  「您的客户端版本与服务器不匹配，请下载更新」

### ISSUE THREAD

**Issue by QSCTech-Sange** [alk3p/EasyConnect-767#5]
Thanks for your EasyConnect to allow me finally witness the client running on my Arch.

However I encounter a problem. When I try to connect my campus network and input the server address, an error is raised as the title mention. That is「您的客户端版本与服务器不匹配，请下载更新」. Is the problem solvable?

Thanks again! Looking forward to your repley!

**Comment by alk3p** [comment]
Don't mention it :)

> https://rvpn.zju.edu.cn/com/installClient_en.html

Consider this patch for PKGBUILD:
```diff
diff --git a/PKGBUILD b/PKGBUILD
index 10739a3..32adbb1 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -1,16 +1,16 @@
 # Maintainer: Leo Yang <webmaster@raspii.tech>
 
 pkgname=easyconnect
-pkgver=linux_01
-pkgrel=1
+pkgver=7.6.7.3
+pkgrel=4
 pkgdesc="Support access to ssl vpn. With easyconect，you can secure and speed up connection to cooperate network at ease!"
 arch=('x86_64')
 url="http://www.sangfor.com.cn"
 license=('custom')
 install=${pkgname}.install
-source=("http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb"
+source=("http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb"
         "http://ftp.gnome.org/pub/GNOME/sources/pango/1.42/pango-1.42.4.tar.xz")
-md5sums=('6ed6273f7754454f19835a456ee263e3'
+md5sums=('89441c8eadab3c6c8f701f32d680d0b6'
           'deb171a31a3ad76342d5195a1b5bbc7c')
 package(){
 	tar xzf data.tar.gz -C "${pkgdir}"
 ```

**Comment by QSCTech-Sange** [comment]
I have been using the release version and I encounter some building problems using this version.

First is
```
PKGBUILD:行20: nporc：未找到命令
```
Another one is
```
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 35, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
```

Is this something wrong associated with PKGBUILD?

**Comment by alk3p** [comment]
Commit 6f7628e --> `nproc` is fixed;
& I'll look into the second problem which I haven't met yet. A suggestion is, checking whether the C compiler works properly or whether the build environment is correctly configured may help.

**Comment by QSCTech-Sange** [comment]
Thanks very much, but sadly new errors merge in compiling Pango.
```
/usr/include/features.h:397:4: 警告：#warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
/usr/include/stdlib.h:140: syntax error, unexpected identifier, expecting ',' or ';' in '# 140 "/usr/include/stdlib.h" 3 4' at 'strtof32'
/usr/include/stdlib.h:141: syntax error, unexpected CHAR, expecting identifier or '(' or '*' in '     char **__restrict __endptr)' at 'char'
/usr/include/stdlib.h:141: syntax error, unexpected ')', expecting ',' or ';' in '     char **__restrict __endptr)' at ')'
/usr/include/stdlib.h:147: syntax error, unexpected CHAR, expecting identifier or '(' or '*' in '     char **__restrict __endptr)' at 'char'
/usr/include/stdlib.h:147: syntax error, unexpected ')', expecting ',' or ';' in '     char **__restrict __endptr)' at ')'
/usr/include/stdlib.h:158: syntax error, unexpected identifier, expecting ',' or ';' in 'extern _Float32x strtof32x (const char *__restrict __nptr,' at 'strtof32x'
/usr/include/stdlib.h:159: syntax error, unexpected CHAR, expecting identifier or '(' or '*' in '       char **__restrict __endptr)' at 'char'
/usr/include/stdlib.h:159: syntax error, unexpected ')', expecting ',' or ';' in '       char **__restrict __endptr)' at ')'
/usr/include/stdlib.h:165: syntax error, unexpected CHAR, expecting identifier or '(' or '*' in '       char **__restrict __endptr)' at 'char'
/usr/include/stdlib.h:165: syntax error, unexpected ')', expecting ',' or ';' in '       char **__restrict __endptr)' at ')'
/usr/include/stdlib.h:233: syntax error, unexpected identifier in '         _Float32 __f)' at '_Float32'
/usr/include/stdlib.h:239: syntax error, unexpected identifier in '         _Float64 __f)' at '_Float64'
/usr/include/stdlib.h:251: syntax error, unexpected identifier in '   _Float32x __f)' at '_Float32x'
/usr/include/stdlib.h:257: syntax error, unexpected identifier in '   _Float64x __f)' at '_Float64x'
/usr/include/stdlib.h:316: syntax error, unexpected identifier, expecting ',' or ';' in '# 316 "/usr/include/stdlib.h" 3 4' at 'strtof32_l'
/usr/include/stdlib.h:317: syntax error, unexpected CHAR, expecting identifier or '(' or '*' in '       char **__restrict __endptr,' at 'char'
/usr/include/stdlib.h:318: syntax error, unexpected typedef-name, expecting identifier or '(' or '*' in '       locale_t __loc)' at 'locale_t'
/usr/include/stdlib.h:324: syntax error, unexpected CHAR, expecting identifier or '(' or '*' in '       char **__restrict __endptr,' at 'char'
/usr/include/stdlib.h:325: syntax error, unexpected typedef-name, expecting identifier or '(' or '*' in '       locale_t __loc)' at 'locale_t'
/usr/include/stdlib.h:337: syntax error, unexpected identifier, expecting ',' or ';' in 'extern _Float32x strtof32x_l (const char *__restrict __nptr,' at 'strtof32x_l'
/usr/include/stdlib.h:338: syntax error, unexpected CHAR, expecting identifier or '(' or '*' in '         char **__restrict __endptr,' at 'char'
/usr/include/stdlib.h:339: syntax error, unexpected typedef-name, expecting identifier or '(' or '*' in '         locale_t __loc)' at 'locale_t'
/usr/include/stdlib.h:345: syntax error, unexpected CHAR, expecting identifier or '(' or '*' in '         char **__restrict __endptr,' at 'char'
/usr/include/stdlib.h:346: syntax error, unexpected typedef-name, expecting identifier or '(' or '*' in '         locale_t __loc)' at 'locale_t'
```
Shall I add some compile parameters? Thanks again and I really appreciate your work so far.

**Comment by alk3p** [comment]
> /usr/include/features.h:397:4: 警告：#warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~

This problem is caused by `g-ir-scanner` and can be ignored.

---

As to syntax errors in `/usr/include/stdlib.h`, try this patch for `src/pango-1.43.0/meson.build`
```diff
--- a/meson.build
+++ b/meson.build
@@ -8,7 +8,7 @@ project('pango', 'c', 'cpp',
         ],
         meson_version : '>= 0.48.0')
 
-add_project_arguments([ '-D_POSIX_C_SOURCE=200809L', '-D_POSIX_THREAD_SAFE_FUNCTIONS', '-D_GNU_SOURCE', ], language: 'c')
+add_project_arguments([ '-D_POSIX_C_SOURCE=200809L', '-D_POSIX_THREAD_SAFE_FUNCTIONS', '-D_BSD_SOURCE', '-D_XOPEN_SOURCE=700', ], language: 'c')
 
 pango_prefix = get_option('prefix')
 pango_libdir = join_paths(pango_prefix, get_option('libdir'))

```
*In my opinion, the errors mentioned above may not really matter.*
& Another suggestion is, checking the build environment ( including the compiler and shared libraries, etc ) may help find the culprit. If you're using Arch Linux ( NOT independent distributions like Manjaro ), it should be the same as below.
```
gcc (Arch Linux 9.3.0-1) 9.3.0
glibc (Arch Linux 2.31-2) 2.31
```

**Comment by QSCTech-Sange** [comment]
It's been fixed. Thank you very much. You are so talented!
